name: KUKLINSKI
markdown: redcarpet
pygments: true

paginate: 4
paginate_path: "/page:num"

relative_permalinks: true
permalink: "/:categories/:title/"

exclude: [npm-debug.log, node_modules, Gruntfile.js, package.json]

ftp_host: 'ftp.kuklinski.com.br'
ftp_dir: '/www'
ftp_passive: false